### ISSUE TITLE
Security scanning

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/messaging-topology-operator#117]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by coro** [comment]
For this, I've essentially mirrored what we've done for the Cluster Operator strategy: https://3.basecamp.com/4467044/buckets/16483566/documents/3218104865

SAST: https://github.com/rabbitmq/messaging-topology-operator/blob/main/.github/workflows/codeql-analysis.yml
SCA: https://app.snyk.io/org/rabbitmqplatform/project/db492385-6bcd-4a1a-a774-745e3097df76
Container Scanning: https://dev.registry.pivotal.io/harbor/projects/46/repositories/messaging-topology-operator

For runtime scanning, since the top-op doesn't deploy anything except the manager binary, I propose we don't need to set up any runtime scanning right now.

@ChunyiLyu @MirahImage Would you be happy with this proposal? If so I will close the issue.
