### ISSUE TITLE
Allow sourcing Queues, Users and Permissions from different namespaces.

### ISSUE THREAD

**Issue by the-smooth-operator** [rabbitmq/messaging-topology-operator#147]
**Is your feature request related to a problem? Please describe.**
Having a RabbitMQ cluster defined in one namespace and resources like Users defined in another namespace is not possible.
This is a very common pattern in Kubernetes with Databases, Monitoring Tools, other infrastructure tooling.

An example is having a RMQ cluster defined in its own namespace and having Application A in "app-a" namespace. The application deployment (for example via Helm Charts) might add a User object in its own namespace which will automatically bootstrap a user in the RMQ cluster.

I'm aware that this was possible before, but was removed because of https://github.com/rabbitmq/messaging-topology-operator/issues/51. This solution completely removes the possibility of having resources in different namespaces instead of letting the option to configure it to the cluster admin.

**Describe the solution you'd like**
I would like to be able to deploy Users in a different namespace that the cluster is defined.

In order to achieve this, Kubernetes operators have taken different options:
 - One option would be to extend the `RabbitMQCluster` CRD (in the RabbitMQ cluster operator repo) adding something like a `allowNamespaces` property which will implement a simple MatchLabelSelector. So the cluster admin will explicitly allow resources in the Namespaces with the chosen set of labels to add users, queues and permissions to that cluster.
 - Other option could be add to this operator a configuration where one can match a RabbitMQ cluster name with a set of labels allowing the resources in the matched Namespaces.
 

**Describe alternatives you've considered**
The alternative solution is not allowing applications to bootstrap their own users and queues an manage this part alongside the RMQ cluster.

**Additional context**
Issue where the functionality was removed https://github.com/rabbitmq/messaging-topology-operator/issues/51

**Comment by MatteoJoliveau** [comment]
I endorse this change, as we would love to use this feature as well since very we want to have a central Rabbit cluster (managed by the platform team) and then let developers manage their own resource (e.g. users) from their app namespaces. There are ways to mitigate #51, for example using a policy system like [OPA Gatekeeper](https://github.com/open-policy-agent/gatekeeper) or Kubewarden(https://www.kubewarden.io/) to prevent users from accessing a cluster they should not use.

**Comment by njbarber** [comment]
@ChunyiLyu would your team be open to accepting an MR around any of the changes suggested above? Would there be a preference?

**Comment by michaelklishin** [comment]
Said applications can always declare the topology they need on application boot, and the cluster Operator won't be able
to prevent that (nor should it). Sorry to be so skeptical but are you really accomplishing much beyond ticking some company-specific practice boxes here?

**Comment by Zerpet** [comment]
Hello @njbarber 👋 

Thank you for submitting the PRs, we welcome any contributions and we are happy to see interest in the Operators 🙂 I comented one of the PRs, and I think we should move here the conversation about potential solutions to tackle this issue.

I acknowledge the use case of "central rabbit cluster" is not covered with the best user experience. However, I think the security concerns in #51 are still valid. Allowing to create topology objects from _any_ namespace feels like making things very easy for an unintended user to gain access to a RabbitMQ cluster. I understand you can put mitigations or impediments via Gatekeeper or Kubewarden, but then we would be giving an additional burden to a human operator, who would have to be responsible of implementing and maintaining those mitigations.

In the same line of thought, allowing topologies from different namespaces would present a few challenges around decision making when a resource already exists. For example, "app A" in namespace "blue" wants to create a vhost "app_a" and a few queues, and "app A" in namespace "red" also wants to create a vhost "app_a" and a bunch of queues. Are those two apps, with the same name and different namespace, meant to share the same vHost? In the event those two apps also share a queue, were the apps designed for sharing a message queue?

Let's say now you decomission "app A" in namespace "blue", the topology operator should not delete the vHost "app_a", because it is used by an app in other namespace. Ensuring this deletion doesn't happen, doesn't seem trivial at a first glance, and it would make the deletion logic complicated.

One solution to meet the "central rabbit cluster" use case, is to create `User` kinds in the same namespace as the "central rabbit", create an RBAC with only read Secrets permissions in the namespace of the "central rabbit", and consume the Secrets from said namespace. Once you have a user, you can create your application's topology using the AMQP protocol, or importing definitions via the HTTP API, from your app. It's not a great solution, in terms of usability, although I think it's more important to make the topology operator secure-by-default, than optimising for this specific "central rabbit cluster" use case.

I'm happy to be convinced otherwise, if we can find solutions to some of the challenges described here.

P.s: this issue is under my radar now, and I will respond in a more timely fashion

**Comment by Zerpet** [comment]
Hello @njbarber 👋 

Thank you for submitting the PRs, we welcome any contributions and we are happy to see interest in the Operators 🙂 I comented one of the PRs, and I think we should move here the conversation about potential solutions to tackle this issue.

I acknowledge the use case of "central rabbit cluster" is not covered with the best user experience. However, I think the security concerns in #51 are still valid. Allowing to create topology objects from _any_ namespace feels like making things very easy for an unintended user to gain access to a RabbitMQ cluster. I understand you can put mitigations or impediments via Gatekeeper or Kubewarden, but then we would be giving an additional burden to a human operator, who would have to be responsible of implementing and maintaining those mitigations.

In the same line of thought, allowing topologies from different namespaces would present a few challenges around decision making when a resource already exists. For example, "app A" in namespace "blue" wants to create a vhost "app_a" and a few queues, and "app A" in namespace "red" also wants to create a vhost "app_a" and a bunch of queues. Are those two apps, with the same name and different namespace, meant to share the same vHost? In the event those two apps also share a queue, were the apps designed for sharing a message queue?

Let's say now you decomission "app A" in namespace "blue", the topology operator should not delete the vHost "app_a", because it is used by an app in other namespace. Ensuring this deletion doesn't happen, doesn't seem trivial at a first glance, and it would make the deletion logic complicated.

One solution to meet the "central rabbit cluster" use case, is to create `User` kinds in the same namespace as the "central rabbit", create an RBAC with only read Secrets permissions in the namespace of the "central rabbit", and consume the Secrets from said namespace. Once you have a user, you can create your application's topology using the AMQP protocol, or importing definitions via the HTTP API, from your app. It's not a great solution, in terms of usability, although I think it's more important to make the topology operator secure-by-default, than optimising for this specific "central rabbit cluster" use case.

I'm happy to be convinced otherwise, if we can find solutions to some of the challenges described here.

P.s: this issue is under my radar now, and I will respond in a more timely fashion

**Comment by njbarber** [comment]
Thanks for the quick feedback @michaelklishin.

I would argue this isn't trying to tick a company-specific practice box.

I can imagine a situation where
- the entire cluster topology isn't known in advance.
- applications are isolated to their own namespace.

In which case
- someone/something with access to the cluster namespace would be responsible for dynamically managing messaging topology resources.
- for some resources, like a user, the relevant credentials wouldn't be available in the requested namespace (in contrast to the suggested changes which would allow for use of the `importCredentialsSecret` field).

**Comment by njbarber** [comment]
Thanks for the quick feedback @Zerpet.

> I understand you can put mitigations or impediments via Gatekeeper or Kubewarden, but then we would be giving an additional burden to a human operator, who would have to be responsible of implementing and maintaining those mitigations.

I agree which is why I took the approach I did.

> In the same line of thought, allowing topologies from different namespaces would present a few challenges around decision making when a resource already exists.

Maybe I'm lacking some context here - but how would that be any different than managing messaging topology resources that exist for the same cluster in a single namespace?

**Comment by Zerpet** [comment]
> Maybe I'm lacking some context here - but how would that be any different than managing messaging topology resources that exist for the same cluster in a single namespace?

The one missing context was me, I thought we were using the object metadata to extract the name of the resource in RabbitMQ 😳 My apologies for the confusion.

Given that we already have the potential name collision problem, a namespace allow-listing solution sounds sensible to me. Let me bring this back to the team to gather more thoughts on this.

Summarising the solution you proposed in the PRs, just to double check we are in the same page:

- There will be an allow-list of Namespaces.
- The Topology Operator will create objects in RabbitMQ if the request comes from a namespace in the allow-list Namespace.
- If the allow-list is empty, the Topology Operator will only create objects when the request comes from the same Namespace as the `RabbitmqCluster` object.

I want to keep the solution description as generic as possible, so we don't bias ourselves towards a concrete solution 🙂 

Next week is going to be holiday heavy for us, so we would likely get back to you the week after.

**Comment by njbarber** [comment]
@Zerpet 

> There will be an allow-list of Namespaces.

There _can_ be.

> The Topology Operator will create objects in RabbitMQ if the request comes from a namespace in the allow-list Namespace.

If the messaging topology resource doesn't define a namespace for its cluster reference it will assume it's in the same namespace. Otherwise that's correct.

> If the allow-list is empty, the Topology Operator will only create objects when the request comes from the same Namespace as the RabbitmqCluster object.

`messagingTopologyNamespaces` can be omitted, in which case the behavior is equivalent to the current implementation.

**Comment by MatteoJoliveau** [comment]
Also, for single tenants scenario, or clusters with very strong isolation mechanisms already in place, could you support a special value `*` to indicate "accept requests for all namespaces"?

I totally agree with the principle of being secure by defaults, but I still think that this option should be given to admins that already have the means to manage such insecurity. By adopting the current implementation as the default and gating the less strict behaviour behind a special value, this feature would basically be opt-in.

**Comment by njbarber** [comment]
@MatteoJoliveau I added this in.

**Comment by MatteoJoliveau** [comment]
@njbarber thank you! Much appreciated

**Comment by Zerpet** [comment]
Hi @njbarber 👋 

Thanks for bearing with us. We discussed this issue and the proposed solution in our sync up; we are happy to accept this change. Moving forward, I'll review both PRs and collaborate with you to get them merged.

**Comment by Zerpet** [comment]
Merged the PR. Thank you @njbarber for the contribution!

**Comment by njbarber** [comment]
@Zerpet thanks for the review!
