### ISSUE TITLE
Cannot use operator with tls enabled rabbitmq cluster

### ISSUE THREAD

**Issue by olfway** [rabbitmq/messaging-topology-operator#233]
## Describe the bug
My rabbitmq cluster has tls certificate for *.some.domain.com,
but topology operator tries to connect to https://operator.test-2.svc:15671 and fail with an error:
x509: certificate is valid for *.test-2.some.domain.com, test-2.some.domain.com, not operator.test-2.svc

But for my applications I have to have a valid *.some.domain.com cert and cannot use self-signed one for operator.test-2.svc

There probably should be a way to provide a hostname for topology operator to connect to

## Version and environment information
- Messaging Topology Operator: 1.1.0
- RabbitMQ Cluster Operator: 1.8.3

**Comment by starkers** [comment]
👍🏼  we're experiencing similar frustrations ourselves

**Comment by Zerpet** [comment]
Hey folks, we discussed this issue in our internal sync up and we are going to prioritise it. We think the Operator should work in any TLS setup and this can be considered a bug. Thank you for reporting this!

**Comment by coro** [comment]
This can be an extension of the `RabbitmqClusterReference` object, removing the implicit assumption that the cluster-local address is fine:

```
type RabbitmqClusterReference struct {
	// The name of the RabbitMQ cluster to reference.
	// +kubebuilder:validation:Required
	Name string `json:"name"`
	// The namespace of the RabbitMQ cluster to reference.
	// Defaults to the namespace of the requested resource if omitted.
	// +kubebuilder:validation:Optional
	Namespace string `json:"namespace"`
	// The hostname used to connect to the RabbitMQ Cluster on which this topology object will be created.
        // If unset, defaults to the cluster-local DNS address `name.namespace.svc`
	// +kubebuilder:validation:Optional
	Hostname string `json:"hostname"`
}
```

**Comment by masterphenix** [comment]
Hello, we are currently blocked with this issue also.
We have production rabbitmq clusters on VMs, and are considering migrating them to Kubernetes by using the cluster and messaging topology operators, which are really promising, easy to use, maintain and monitor. 
However, not being able to use a trusted certificate alongside with the Messaging Topology Operator is blocking us, and prevents us from going further at this point.
Any estimate on when a fix could be released ? Or maybe a workaround in the mean time ?

**Comment by logineimer** [comment]
Same here. It'd be great if there was a fix soon.

**Comment by Zerpet** [comment]
> This can be an extension of the `RabbitmqClusterReference` object, removing the implicit assumption that the cluster-local address is fine:
> 
> ```
> type RabbitmqClusterReference struct {
> 	// The name of the RabbitMQ cluster to reference.
> 	// +kubebuilder:validation:Required
> 	Name string `json:"name"`
> 	// The namespace of the RabbitMQ cluster to reference.
> 	// Defaults to the namespace of the requested resource if omitted.
> 	// +kubebuilder:validation:Optional
> 	Namespace string `json:"namespace"`
> 	// The hostname used to connect to the RabbitMQ Cluster on which this topology object will be created.
>         // If unset, defaults to the cluster-local DNS address `name.namespace.svc`
> 	// +kubebuilder:validation:Optional
> 	Hostname string `json:"hostname"`
> }
> ```

I've started working towards this solution, but I'm unsure about the user experience with this approach. Essentially, down this road, a user would have to update all existing topology objects and update the `rabbitmqClusterReference`, which is prohibited by our webhooks, leading us to also change the webhooks for all our types; what an insane amount of work for us and for the users, just to pass a domain suffix!

More over, the cluster domain is ~never~ unlikely to change and it's very likely always the same, therefore I don't see much reason to make the domain suffix configurable per topology object. It seems more sensible to configure this property once, and apply it to all topology objects.

Given the above, I'm considering two options:

1. Provide an command-line option and env var to configure the cluster domain suffix
2. Do a CNAME DNS query in the main function, on startup, and figure the domain suffix

Option 1 has the downside that users won't be able to just `kubectl apply -f <link to manifest>`, as they will have to add this environment variable or CLI option in the args.

Option 2 has the downside that we have to assume that some service exists, probably the `kubernetes.default.svc`. We can always fallback to no-domain name if this service does not exist, or the query is not successful. This also assumes that the DNS service allows for CNAME queries.

Does anybody have a preference?

**Comment by masterphenix** [comment]
Hello, thank you for your work on this. What about doing both ? Do a DNS check if no command-line option or env var is provided, otherwise, use command-line option / env var ?

**Comment by Zerpet** [comment]
Sounds reasonable. As a first iteration, we can lookup an env var, if not present, perform a DNS lookup, if that fails, use an empty domain name. We can add the command-line option later if the env var does not suffice.

**Comment by Zerpet** [comment]
I have some changes locally with this behaviour; however, during QA, I noticed that, if we perform a DNS lookup and append the domain name when the env var is not present, we are changing the default behaviour, which can be breaking in certain scenarios. For example, our internal testing generates certificates with the short name e.g. `tls-server.rabbit.svc`, and our tests were broken by this change.

I was planning to release this change as part of a minor release, and as we don't ship (or avoid as much as possible) breaking changes in minors, I'm going to leave the DNS lookup out of the changes. If the env var `KUBERNETES_CLUSTER_DOMAIN` is present, it will be appended to the shortname extracted from the Service; otherwise it will use the short name. In this way, we can introduce the change in a minor as the default behaviour is identical to the current one.

The last bits needed to finish of this issue are documentation changes. I think there's also a need to provide a small guide on how to "inject" a custom CA into the Topology Operator, as I faced some certificate trust issues during QA. If your certificates are signed by a well known CA, everything should JustWork™.

Given that holiday season starts today for me, this change is unlikely to make it to a release until some time in January. For the very impacient 🙂 If you have Docker installed, you can build an OCI image by checking out the branch `issue-233` and running:

```
# This builds and pushes a dev image to DockerHub
make docker-build-dev GIT_COMMIT=dev DOCKER_REGISTRY_SERVER=my-dockerhub-user OPERATOR_IMAGE=messaging-topology-operator
```

Then grab a manifest from the releases page, and modify the `Deployment` to include the env var `KUBERNETES_CLUSTER_DOMAIN` with a string value e.g. `example.com` **and** modify the image to use the one built in the previous command.

**Comment by masterphenix** [comment]
Hello,
I just tested the image based on branch `issue-233`, the operator does take the environment variable into consideration, but unfortunately, there still is a `<namespace>.svc` in the domain name (I have replaced my real domain with example.com below) :

```
{"level":"error","ts":1640596268.1266189,"logger":"controller.user","msg":"Reconciler error","reconciler group":"rabbitmq.com","reconciler kind":"User","name":"rabbitmq-euw-sandbox02-operator-user","namespace":"rabbitmq-system","error":"Put \"https://rabbitmq-euw-sandbox02.rabbitmq-system.svc.example.com:15671/api/users/operator\": dial tcp x.x.x.X:15671: connect: connection timed out","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:227"}
```
The problem lies in the fact that there are 2 different domains :
- The kubernetes internal domain, which does not have a valid certificate (namespace.svc.cluster.local)
- The public domain (example.com), with a valid certificate for *.example.com, and that we would like to use

Also, the name of the env var is confusing, because it suggest that we are changing the kubernetes internal domain, which to me, is not what is intended.

**Comment by Zerpet** [comment]
Hey everyone, happy new year 🎉 

Thank you @masterphenix for trying out the changes and taking the time to provide feedback. I (incorrectly) assumed you changed the Kubernetes internal domain. Based on that assumption, it seemed ok to "borrow" the same env var name used for Kubernetes internal domain. I'm happy to change the name of the env var, I don't have any strong opinion on that regard.

The challenge I see to implement your scenario, is constructing a URL with the correct domain name. In the Operator, when we receive a reconcile request, we have the **custom resource name**, its **namespace** and a `RabbitmqCluster` reference (**name** + **namespace**). For example, `myqueue.default` for a queue resource and `myrabbit.default` as RabbitMQ reference. Just with those two bits of information, plus anything we provide via env vars, we have to construct the URL to access RabbitMQ Management API. 

In your scenario, how would I construct the URL for **any** RabbitMQ ?

P.s: since this comment is going to send a notification to a few people 🙂 It would be very helpful if you could react with a 👍 or with a 🚀 if the current state (connect using `resource name` + `namespace` + `svc` + `custom-domain`) would work for you. Or with a 👎 or  👀 if the current state won't work for you.

**Comment by masterphenix** [comment]
Hey everyone, happy new year !

From what I understand on how the topology operator works, it needs the following to work:

1. A kubernetes cluster domain, which is used by the webhook to watch for changes on k8s resources ; in my scenario, this domain is the default one '.svc.cluster.local', which gives this FQDN : myrabbit.rabbitmq-system.svc.cluster.local ; everything seems fine to me regarding this feature.
2. An http(s) address, which requires a valid certificate, to communicate with the rabbitmq API. In my scenario, this address looks like this : myrabbit.example.com ; this is the URL I would like to be able to customize.

To me, both these URL should be distinct, because they serve different purpose. What about having an env var in which we provide the whole URL, a  bit like @starkers [suggested ](https://github.com/rabbitmq/messaging-topology-operator/issues/233#issuecomment-919239021)?

**Comment by Zerpet** [comment]
I'm inclined to go for that solution, an annotation to specify a hostname or FQDN. `RabbitmqCluster` objects would be annotated with such information, and the Topology Operator will consume it, if present. I need to give it a bit more thinking from the security point of view, and bring it up with the team.

**Comment by Zerpet** [comment]
I just merged #310, which adds support for configuring a custom domain name to be appended to the `resource name` + `namespace` + `.svc` via the env var `MESSAGING_DOMAIN_NAME` in the Topology Operator Deployment. If the env var has a value e.g. `example.com`, it will be appended to the URL inferred from the Custom Resource name and the Service name, e.g. `my-rabbit.my-namespace.svc.example.com`.

For the second part described in this issue, where rabbitmq is exposed at an external URL e.g. `my-rabbit.example.com`, it can be resolved using the connection secret feature in #294, and documented [here](https://rabbitmq.com/kubernetes/operator/using-topology-operator.html#non-operator).

The track of work in #294 had a clear overlap with the initial intention in this PR of providing an annotation to connect to an arbitrary URL, and we decided to implement a more generic solution as delivered by #294 and #296.

The env var solution will be available in the next release. The connection secret feature is available since 1.4.0. The last bit of work here is to document the new env var.

**Comment by Zerpet** [comment]
Merged PR for docs https://github.com/rabbitmq/rabbitmq-website/pull/1365

**Comment by logineimer** [comment]
Thanks for your effort, @Zerpet. However, the solution in #296 you linked targets environments running unmanaged clusters which requires extra credentials for the management api. Imo this issue was (at least partially) created for the situation when you want to manage objects on an operator managed cluster which is exposed via TLS to the public internet without providing credentials. I don't see how this is resolved now? 😯

**Comment by Zerpet** [comment]
The idea in #296 came from the need of using Topology Operator with unmanaged clusters, but the solution provided is not tied or limited to unmanaged clusters. For example, if you have a managed cluster exposed via `rabbit.example.com`, you can create a Secret matching the default user credentials and add the `uri` field with the value `https://rabbit.example.com`. In that regards, the Topology Operator does not check whether the HTTP URI is from a managed or unmanaged RabbitMQ cluster.

I understand it can be inconvenient to copy the default user credentials in its own Secret. To alleviate that, you can define default user credentials using `rabbitmqcluster.spec.rabbitmq.additionalConfig` and use the configuration keys `default_user` and `default_pass`, then use those same credentials when you generate the `connectionSecret` https://github.com/rabbitmq/messaging-topology-operator/blob/0212063fe31ce1df9b06053bfc4dde809c87c31e/docs/examples/non-operator-managed-rabbitmq/queue.yaml#L21-L23

I guess grabbing the default user credentials automatically would be convenient, but it is not strictly necessary to resolve this issue.

**Comment by masterphenix** [comment]
Thank you @Zerpet for these clarifications. 
However, the fact that the secret must be in the same namespace as the object is not ideal at all.
In our context, we would like our dev teams to be able to create queues, exchanges, etc. in their own project namespaces, and creating a secret with management access in each namespace is just not possible.
For this solution to be usable, we should be able to provide the namespace in which the 'connectionSecret' resides.

**Comment by Zerpet** [comment]
I agree that managing a 'management' Secret across multiple namespaces is not ideal. I think there's value in consuming annotations from `RabbitmqCluster` objects to customise the URL used by the Topology Operator. Unfortunately, I'm working on something else and I won't be able to revisit this for some time.
As a workaround to alleviate the pain of Secrets across namespaces, I'd recommend to try [SecretGen Controller](https://github.com/vmware-tanzu/carvel-secretgen-controller). We use it internally for this same use case, among others, like using image pull secrets in multiple NS.

**Comment by ChunyiLyu** [comment]
@davemaul @olfway @masterphenix Support for custom URI when connecting to a rabbitmqcluster is just added via #644. You can now annotate the rabbitmqcluster with the custom connection URI and there's no need to create an additional secret. This feature is in the current main branch and coming soon in the next release of the operator.
