### ISSUE TITLE
Leverage CR secretbackend configuration to authenticate with cluster

### ISSUE THREAD

**Issue by twhite0** [rabbitmq/messaging-topology-operator#239]
#### Context
Given the great work occurring within the [vault-integration](https://github.com/rabbitmq/cluster-operator/tree/vault-integration) branch.  Would like to propose enhancing the operator to leverage the `secretbackend.vault` of the CR to pull the rabbitmq cluster credentials. 

#### Scope
Enhance the MTO to conditionally pull credentials from Vault leveraging the CR configuration of the RabbitmqCluster.  

#### Concerns
*  Shovel and Federation configurations.

cc: @georgeharley

**Comment by twhite0** [comment]
#### Initial assessment
*  Controllers all leverage [ParseRabbitClusterReference](https://github.com/rabbitmq/messaging-topology-operator/blob/868f81e832aba8568eb96663d254b8b27ed53f7b/internal/cluster_reference.go#L21) to capture the specifics of the cluster.
*  Currently the admin cluster credentials are [retrieved into a Secret](https://github.com/rabbitmq/messaging-topology-operator/blob/868f81e832aba8568eb96663d254b8b27ed53f7b/internal/cluster_reference.go#L55-L58) sourced from the Secret created by the default cluster-operator provisioning process.
*  The Controllers leverage the [generateRabbitholeClient](https://github.com/rabbitmq/messaging-topology-operator/blob/main/internal/rabbitmq_client_factory.go#L58) to build the API client.  Pulling the [username & password](https://github.com/rabbitmq/messaging-topology-operator/blob/main/internal/rabbitmq_client_factory.go#L64-L72) from the Secret.

The ParseRabbitClusterReference would need to be modified to (options):
1. Identify the admin secret storage in use, fetch the username&password and continue to return it using a k8s Secret
1. Identify the admin secret storage in use, return an Interface to retrieve the secret.

**Comment by twhite0** [comment]
We would be very interested in contributing energy (research/code ~ PR) towards this effort.  While we're eager to build on the cluster-operator Vault work being performed, we don't want to get to ahead of ourselves.  We'd like to ensure the feature aligns with the product.  Looking forward to further discussions.

**Comment by ansd** [comment]
Hey @twhite0, thanks a lot for initiating this discussion and for contributing.

The topology operator will dynamically fetch the default user credentials from Vault using the [Vault Go Client](https://github.com/hashicorp/vault/tree/main/api).

To do so, when parsing the RabbitmqCluster reference, instead of getting `cluster.Status.DefaultUser` for fetching the K8s Secret, it should get the `cluster.spec.secretBackend.vault.defaultUserPath`. Thereafter, it should query Vault for the credential.

Option 2 in [your comment above](https://github.com/rabbitmq/messaging-topology-operator/issues/239#issuecomment-925793774) sounds better. The code needs some refactoring: [generateRabbitholeClient](https://github.com/rabbitmq/messaging-topology-operator/blob/b3ffeaaa4bd8c6feb37abe152784413aa044093e/internal/rabbitmq_client_factory.go#L58) should probably accept username and password directly instead of a `secret *corev1.Secret`. Likewise, [ParseRabbitmqClusterReference](https://github.com/rabbitmq/messaging-topology-operator/blob/868f81e832aba8568eb96663d254b8b27ed53f7b/internal/cluster_reference.go#L21) should not return a `secret *corev1.Secret` anymore. Instead it returns some other `SecretFetcher` interface / struct or the username and password directly.

Before jumping too much into the implementation details, I'd suggest to start implementing a spike first to see everything work end-to-end and to gain a better understanding how everything fits together. (No need to write unit tests / generate mocks etc in the spike.)

Some open questions to be figured out in the spike:
1. Will the topology operator be assigned its own Vault role with policies to read all the RabbitmqCluster default user credentials? 
2. If [Vault TLS](https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/vault-tls) is enabled, will the topology operator fetch the CA cert from Vault once upon topology operator pod start, and trust it? Will we configure the topology operator with a Vault path where to fetch that cert?

**Comment by twhite0** [comment]
@ansd:  Thanks for the openness to enhance the operator and for your initial thoughts.  We'll follow your guidance and start with the mechanics.  We'll look to start early next week.  A colleague of mine (@georgeharley) will be doing the heavy lifting.  

Let us know if there's additional feature/spike process you'd like us to follow.

**Comment by georgeharley** [comment]
Hi @yaronp68 and @ansd. Is there any outlook available please on when someone might get a chance to cast an eye over draft PR #255 ? Any feedback you can spare us would be very gratefully received.

**Comment by MarcialRosales** [comment]
Hi @georgeharley I started reviewing it last Friday but i have been away Monday & Tuesday. I resume the review today.

**Comment by twhite0** [comment]
as mentioned above, the issue is currently delivered as a part of a draft PR.  The team paused for the holiday season and agreed to pick it up first thing in the new year (2022).

**Comment by ChunyiLyu** [comment]
Related PR has been merged: https://github.com/rabbitmq/messaging-topology-operator/pull/255 Thank you @georgeharley for contributing!

Closing issue.
