### ISSUE TITLE
make default log timeformat human readable

### ISSUE THREAD

**Issue by ArgTang** [rabbitmq/messaging-topology-operator#241]
**Is your feature request related to a problem? Please describe.**
`{"level":"info","ts":1632735489.3334155, ...}`
the ts field in the logs is not human readable. 

**Describe the solution you'd like**
The logs print timestamp with ex. iso8601 formatting

**Comment by ansd** [comment]
I think the default time format of the JSON logs should stay a Unix time stamp because
1. That's what's defined in the [Kubernetes JSON log format](https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#json-log-format): `ts - timestamp as Unix time (required, float)`
2. That's the default of the [zap production mode logger used in controller runtime](https://github.com/kubernetes-sigs/controller-runtime/tree/master/pkg/log/zap).
3. Above 2 points seem to me a very good default because in production, you'll have a logging backend. Every decent logging backend (or even earlier on the log shipper) can convert the time format from unix timestamp to whatever human readable time format you prefer.
4. If you don't run the operator in production, use the `--zap-devel` command line flag in the operator deployment. It will print more human-readable output, i.e. no JSON and human readable time format, e.g. `2021-09-30T10:08:41.229Z	INFO	controller-runtime.manager.controller.rabbitmqcluster	Finished reconciling ...`

**Comment by ArgTang** [comment]
Thanks for the tips. we'll see if we can work around this

**Comment by Zerpet** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
