### ISSUE TITLE
Resource deleted in admin interface is not recreated before restarting operator

### ISSUE THREAD

**Issue by ArgTang** [rabbitmq/messaging-topology-operator#243]
## Describe the bug
Manually deleted resources are not reconciled before operator restart

## To Reproduce
1. deploy a resource ex a policy or a user
2. login with default user and delete resource
3. The resource do not come back

4. restart topology-operator pod. 
5. resources are reconciliation again

**Expected behavior**
if a resource is deleted manually from management console, next reconciliation loop from operator should re-add the resources.
If there is no loop, i guess this is a feature request for adding a timer to run reconciliation once per x min. maybe 5min. 

## Version and environment information
- Messaging Topology Operator: 1.1.0
- RabbitMQ: [e.g. 3.8.22]
- RabbitMQ Cluster Operator: 1.8.3
- Kubernetes: 1.20.7

**Comment by Zerpet** [comment]
The challenge in this scenario is to "notify" the operator that something has changed inside RabbitMQ. The operator is only aware of changes to the resource it owns in Kubernetes layer. RabbitMQ server is a different layer, and the operator is not aware of events in this layer. 

There's no straightforward way to "watch" events happening inside RabbitMQ, without doing something complicated with a sidecar and forcing all users to use the event exchange plugin, which seems like an undesirable solution.

Running a reconciliation loop on a fixed timer is not a great solution either, because the operator might own a decent number of objects, and most of the time, it won't do much work other than logging a lot of "reconciliation success" messages. It also makes it very hard to reason about the causes for a reconciliation i.e. why was the reconcile triggered?, as it can trigger by an event, or by the fixed timer.

You can always trigger a reconciliation loop by modifying a resource metadata e.g. adding/updating a label, which will trigger a reconciliation for just that object, instead of restarting the operator.

**Comment by ArgTang** [comment]
np, thanks for the update :) . the operator works very well as is, this is "just" a ux weirdness

**Comment by movergan** [comment]
The time-triggered reconciliation of all objects could've been pretty useful. We are facing a cluster to be completely destroyed and recreated due to Google's preemptible node pool. But even though it's a brand new cluster that is up and running, there are no users, permissions, etc. And topology operator is not aware of the fact that the cluster is recreated. A manual restart of the operator pod quickly fixes the issue. But we want it to be automatic.

**Comment by Zerpet** [comment]
Good news for anyone interested in this issue. @ChunyiLyu found a way to make this possible in the Topology Operator. It will be an opt-in feature; in other words, by default, it won't perform time based reconciliation. You can opt-in into this feature by configuring the Topology Operator with a specific environment variable.
