### ISSUE TITLE
Is there helm creating order issue

### ISSUE THREAD

**Issue by ChongDeng** [rabbitmq/messaging-topology-operator#261]
If putting all api objects, such as vhost, exchange, queque, federation,  secret，permission in  a yaml file, let's say demo.yaml, 
and then use helm to create these customerized api objects via demo.yaml, will there be dependancy issue？

  For example, exchange depends on vhost, and federation depends on user. So, is it possible that helm create user before creating federation, and then cause problematic federation？

**Comment by Zerpet** [comment]
There could be an ordering issue in the situation you described, however, once all objects are created, all the necessary objects will be created, when the requisites are met. For example, the exchange object may be created first, and it will fail to declare the exchange because the vhost does not exist. Later, when the vhost object is created, and the vhost is created inside RabbitMQ, the exchange declaration will succeed.

When the Topology Operator fails to create a topology object inside RabbitMQ, it requeues the request and tries again some time later, therefore, all objects will be created eventually.

**Comment by fqyyang** [comment]
@Zerpet OK, got it. That's so great. Thanks for the detailed explanation.

**Comment by ChongDeng** [comment]
@Zerpet OK, got it. That's so great. Thanks for the detailed explanation.
