### ISSUE TITLE
Use the operator to create users

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/messaging-topology-operator#3]
**Describe the solution you'd like**

- crd name: users.rabbitmq.com
- all configurations
- follow the [provision service duck type spec](https://k8s-service-bindings.github.io/spec/#provisioned-service) (for the crd status and its secret format)  

**Additional context**

**Comment by coro** [comment]
@n3wscott We have a couple of options for the `username` and `password` provided by the object. We can either create a random username/password and return it to the user in the secret referred to in the Status, or allow the user to provide pre-defined username/passwords to populate the binding secret with. Is there a use case in knative for the pre-defined use case, or can we proceed with the former option?

**Comment by n3wscott** [comment]
For me, it does not make much sense to have the application data (non-secret things) in the secret, but it also does not harm. But it is an antipattern to have that be the only place the data about how to find the broker (url, port) is kept.

For providing the username and password, I would like to provide a secret to the instance of a broker CO in it's spec. The controller can read in and validate that data, use it and reconcile it when the data changes. Then have the current username/password reflected in a secret the controller owns that I can use to configure things that point at this Broker. If no secret is provided in the spec, keep on making random ones.

Does that make sense @coro ?

**Comment by coro** [comment]
I do agree with @st3v's comment on the need for an abstraction above user for a binding. I'd almost rather create a new controller for it upfront rather than make the user controller have to retrieve cluster info e.g. hostname.

@n3wscott Your suggestion makes sense to me. I believe that in order to avoid having two sources of truth for the credentials of the user, the controller would have to create a Secret with the credentials if one is not provided, or 'repurpose' the one provided in the User Spec, rather than creating a second one. I _believe_ it's possible for the controller to set the owner reference for this pre-existing secret, though I'm not 100% sure!

This way, as you say, any updates to the Secret will trigger the User object reconciliation.

**Comment by n3wscott** [comment]
@coro In the model we are using, what is in the spec is not the source of truth, it is just the request to make the world look this way. The source of truth should be a new secret that is ref'ed in the status of the CO and owned by your controller. This why if I change my password in my secret, you can detect the change and choose to ignore it and provide a condition with an error reflecting the choice to ignore it. Then downstream consumers of the status of the CO are always up to date.

You might also want to make your own secret because you might protect those downstream consumers from me deleting the secret I provided in the CO spec. Make sense? We do this in the knative rabbitmq broker now for the rabbit cluster secret that is created. We don't consume your secret directly.

**Comment by coro** [comment]
I've just merged the PR to allow create/delete users in this operator. I think there's three threads from this issue that I'd like to progress, so I'm planning to spin them out into other issues linking to this issue:
* Support updates to User resources & credential Secrets
* Allow pre-defined passwords to be used for created User objects
* Provide a Provisioned Service Binding custom resource

@ChunyiLyu @MirahImage @st3v @n3wscott let me know if there's anything you'd add / disagree with.
