### ISSUE TITLE
Allow/support operator deployment via OperatorHub on OpenShift 4.12+

### ISSUE THREAD

**Issue by shanehughes** [rabbitmq/messaging-topology-operator#692]
**Is your feature request related to a problem? Please describe.**
This Operator, when deployed via OpenShift's OperatorHub component (community-operators-prod repo) is being limited to OpenShift v4.11. Currently, we can only install up to 1.10 (which doesn't have this annotation).

**Describe the solution you'd like**
The `metadata/annotations.yaml` (in the community-operators-prod repo) contains `com.redhat.openshift.versions: "v4.7-v4.11"` - could we expand this to higher versions? Or perhaps removed? 4.14 is on the radar if that helps (not sure if there are any kube API related issues that need to be addressed in that version.

**Describe alternatives you've considered**
We've been able to install 1.12 using the non-olm managed approach, but would prefer not to have to manage the YAML long term and there are management advantages to using OperatorHub. 

Happy to help out somehow, but not sure how you manage the lifecycle in the community-operators-prod repo.

**Comment by DanielePalaia** [comment]
Hi @shanehughes,
yes I noticed that issue a few months ago and provided a fix in our OLM script:

https://github.com/rabbitmq/OLM-Package-Repo/commit/1dbfc6312433ba19f2283f317a6b394a7d405b75

That annotation was necessary in the past in order to skip the release for v4.6 of openshift as there were some issues with OLM webhook certificates for that version and the redhat openshift marketplace tests were failing  just for that specific version.

Now that version is not running anymore as part of their tests so the label can be removed.
 
What it happens is that after every release of this operator, this github action:
https://github.com/rabbitmq/messaging-topology-operator/blob/main/.github/workflows/operatorhub.yml

will use this script:
https://github.com/rabbitmq/OLM-Package-Repo

In order to generate the OLM package from our manifests and push it to operatorhub/openshift marketplace repo

The fact is that since I made the modification no new version of the operator was indeed released and so the fix wasn't pushed yet.

I think in the next release of the operator it will be present also for newer openshift version

**Comment by shanehughes** [comment]
Makes sense, thanks for the update. Is there any chance we could run off a new release? I note there's been quite a few updates since the last release available to OpenShift clusters > 4.11 (which is 1.10.0). Perhaps even just a z-channel bump to 1.12.1?

**Comment by DanielePalaia** [comment]
HI @shanehughes yes we released version v1.12.1 and submitted PRs to operatorhub and openshift-marketplace:

https://github.com/k8s-operatorhub/community-operators/pull/3502
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3572

I think it will take some time for tests to be validated and for final approval

**Comment by shanehughes** [comment]
Fantastic! Thanks so much. Looks like both PRs have been merged successfully.
