### ISSUE TITLE
Add support for vhost-scoped parameters

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/messaging-topology-operator#85]
**Is your feature request related to a problem?**
We would like to use [Parameters](https://www.rabbitmq.com/parameters.html#parameter-management) via Kubernetes API, so that we can configure features like the [Schema Replication Sync](https://www.rabbitmq.com/definitions-standby.html). 

**Describe the solution you'd like**
A new property in the VHost kind to represent parameters. A vHost can have any number of parameters. A parameter is a combination of `key` and `value`, where key is a string and value can be anything, represented as a string e.g. JSON, string, integer, etc.

**Describe alternatives you've considered**
A new CRD to represent a parameter in RabbitMQ. Parameters can be either global or vhost scoped.

This alternative is not the best because this fits better as a property of the vHost object.

**Additional context**
The value of the properties seems to be an object, represented most of the time via JSON. There is an unknown to explore as to what type or format is the value property expecting.

**Comment by Zerpet** [comment]
**[SYNC UP]**
- Global parameters could be a property in Cluster Operator Spec.
- Vhost scoped parameters could be a property of the Vhost object Spec.

**Comment by ChunyiLyu** [comment]
Rather than allowing people to specific any runtime parameters, it makes more sense to enable our users from the perspective of what they are trying to achieve. For example, we can have specific crds to help people create shovel definitions or federation upstream, users don't have to know that configurations are done through runtime parameters. Closing this issue for now
