### ISSUE TITLE
Mass reconciliation of RMQ objects

### ISSUE THREAD

**Issue by AntonAleksandrov13** [rabbitmq/messaging-topology-operator#864]
Hi, 
We are facing the following behaviour of the operator:
Once in a while, the operator decides to reconcile all objects that can be seen from queue depth of each controller:
<img width="1831" alt="Screenshot 2024-08-02 at 1 09 29 PM" src="https://github.com/user-attachments/assets/1dd068cb-1bf9-4bbb-9eca-f1b473670a61">

This seems weird because we don't use [time based reconciliation](https://www.rabbitmq.com/kubernetes/operator/using-topology-operator#sync-period) and we don't run a mass update of all RMQ objects in our cluster. 

I am reporting this here as I am not sure if it's a bug or not. 

Operator version: 1.12.0
EKS version: v1.25.16-eks-db838b0

**Comment by Zerpet** [comment]
The Operator does not reconcile an object unless there's an event for said object. It watches for updates/deletes of any kind i.e. updates to the spec and/or the metadata. The other situation where all objects are reconciled is after the Operator restarts.

**Comment by AntonAleksandrov13** [comment]
Hi @Zerpet 
Sorry it took a while for me to come back to this. I had an opportunity to do proper digging into this and I can finally explain this behavior.

For now I am fairly confident this happened because `managerOpts.Cache.SyncPeriod` has a default value of 10 hours(+- 10% jitter) based on [docs](https://github.com/kubernetes-sigs/controller-runtime/blob/d0396a3d6f9fb554ef2da382a3d0bf05f7565e65/pkg/cache/cache.go#L146-L171). So every 10(+- 1) hour we would have to sync all the objects. 
The problem is that this causes scaling issues in our platform. When this sync happens, we have to reconcile 75k+ objects, From our observations, a reconciliation of a new added object during sync reconciliation takes about 20-30 minutes. Which means that we have to wait until all the old objects are reconciled before adding more new ones. 

We can set syncPeriod to a higher value, but the more objects we create the more we have to push syncPeriod value. 


I have noticed that the operator does not set [MaxConcurrentReconciles](https://github.com/kubernetes-sigs/controller-runtime/blob/e3347b5405cdd0da5bff527af3d406117938ba6b/pkg/controller/controller.go#L46). Is there a reason against using more workers? 

Also, we tried scaling the operator to 2 replicas with hopes that we can could process reconciliation in parallel, but the second replica works like a failover replicas, I guess. Are there any plans to support parallel queue processing between replicas?

**Comment by Zerpet** [comment]
Oh, wow 😮 I didn't know controller runtime was setting a default like that on us. 

I did some digging, and ended up in the [client-go cache](https://pkg.go.dev/k8s.io/client-go/tools/cache#NewSharedIndexInformerWithOptions) module, thanks to https://github.com/kubernetes-sigs/controller-runtime/issues/521

Fortunately, you can change the [Topology Operator sync period using environment variables](https://www.rabbitmq.com/kubernetes/operator/install-topology-operator#modifying-the-rabbitmq-messaging-topology-operator-default-configuration). You will have to change the manifest of the operator, add the env var `SYNC_PERIOD` and set it to `"0"`. That should disable the resync period.

I'm not keen to modify the default, since there are some good arguments to keep a default of 10 hours. I will update our docs, as currently they state `By default, sync period is disabled, and reconciliation happens only when owned resources are updated.`, which is simply not true.

Thank you so much for digging and sharing the root cause!

**Comment by michaelklishin** [comment]
The docs were updated by @Zerpet in https://github.com/rabbitmq/rabbitmq-website/pull/2134.
